### ISSUE TITLE
Migrate dev team jenkins jobs to centos-ci

### ISSUE THREAD

**Issue by r0h4n** [usmqe/usmqe-centos-ci#13]

**Comment by dahorak** [comment]
I've updated the related PR https://github.com/Tendrl/usmqe-centos-ci/pull/1.

The srpm packages are prepared on so called _build_server_, which is machine requested from [Duffy](https://wiki.centos.org/QaWiki/CI/Duffy) (we have full access to the machine and we can install/configure there anything what we need).

To save some resources, there is implemented some basic sharing of the _build_server_ between multiple package build jobs. Basically, when new build job is launched, it will check if there is existing _build_server_ and if yes it will use it, otherwise it will trigger auxiliary job to prepare new one. Similarly at the end during teardown process, it will check if the _build_server_ is still used by some other job and if not, it will return it back.

**Comment by dahorak** [comment]
Following issues needs to be fixed to be able to build the packages (without further workarounds):
https://github.com/Tendrl/api/issues/202
https://github.com/Tendrl/api/issues/209
https://github.com/Tendrl/dashboard/issues/442

**Comment by dahorak** [comment]
Building packages from master and release/* branch is working, so closing this issue.
Please create new one, if there is any other request.
